NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GD5DJQDDBKGAYNEAXU562HYGOOSYAEOO6AS53PZXBOZGCP5M2OPGMZV3",
"GAENZLGHJGJRCMX5VCHOLHQXU3EMCU5XWDNU4BGGJFNLI2EL354IVBK7",
"GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="POPORING"
ORG_URL="http://poporing.tech"
ORG_LOGO="http://poporing.tech/popo.png"
ORG_DESCRIPTION="Description of issuer"
ORG_PHYSICAL_ADDRESS="Europort Rondabout Westside Reclmatopn Gibraltar"
ORG_PHONE_NUMBER="82 (010)-6868-2905"
ORG_OFFICIAL_EMAIL="poporing2021@gmail.com"

[[PRINCIPALS]]
name="James Park"
email="kimjames8181@gmail.com"

[[CURRENCIES]]
code="POPO"
issuer="GBDFOFSQIIQNN5IMOLST2X7DKQZ3RNNPPLNKNGJNIKAVTAP33OQDD7EZ"
is_asset_anchored="false"
display_decimals=7
name="POPO COIN"
desc="POPO COIN IS POPORING GAME'S TOKEN."
image="http://poporing.tech/popo.png"
fixed_number=999999999
